source "http://rubygems.org" do
    group :external_gems do
        gem 'rspec', '3.7.0'
        gem 'rspec-retry', '0.6.1'
        gem 'factory_bot', '5.1.1'
        gem 'require_relative'
        gem 'nokogiri', '~> 1.10', '>= 1.10.10'
        gem 'faker', '~> 2.11'
    end
end

source 'https://MVZrB-4Zc1vt8x1SeDnEYfymn3cBjVWVo@gem.fury.io/seekr/' do
    group :internal_test_gems do
        gem 'hi_httparty'
    end
end